### ISSUE TITLE
Placeholder text in form is inconsistently capitalised [Minor]

### ISSUE THREAD

**Issue by Coletterbox** [fac-17/MNOP#46]

**Comment by Albadylic** [comment]
Also, font in "Say something" box is inconsistent 

[tiny issue ofc]

**Comment by Coletterbox** [comment]
The footer capitalisation also has a minor issue. In theory it's all just one sentence, so "In" doesn't need to be capitalised; the exclamation point at the end of your company name only **looks** like it's ending the sentence.

**Comment by andy-mc-donald** [comment]
Fixed thanks :)
