### ISSUE TITLE
HTML5 5 semantics - div -> article

### ISSUE THREAD

**Issue by xIrusux** [fac-17/MNOP#49]
https://github.com/fac-17/MNOP/blob/078a1285f4254b92548d3cb4af7baa57c462ed10/index.html#L54

Hi everyone! 

Super minor thing. I have seen that in the rest of your page you have followed HTML5 and used "article" instead of  "div". Only in this one incident the div is still there.

**Comment by georgiamshaw** [comment]
completed! thank you!
